using FluentAssertions;
using NSubstitute;
using Trackly.Application.Common.Interfaces;
using Trackly.Application.Features.ClientRoom.Queries.GetSummary;
using Trackly.Domain.Entities;
using Trackly.Domain.Enums;

namespace Trackly.Application.UnitTests.Features.ClientRoom.Queries.GetSummary;

public class GetClientRoomSummaryQueryHandlerTests
{
    private readonly IProjectRepository _projectRepository = Substitute.For<IProjectRepository>();
    private readonly IContractRepository _contractRepository = Substitute.For<IContractRepository>();
    private readonly IMilestoneRepository _milestoneRepository = Substitute.For<IMilestoneRepository>();
    private readonly ITicketRepository _ticketRepository = Substitute.For<ITicketRepository>();
    private readonly IApprovalRepository _approvalRepository = Substitute.For<IApprovalRepository>();
    private readonly ICurrentClientRoomService _currentClientRoom = Substitute.For<ICurrentClientRoomService>();

    private GetClientRoomSummaryQueryHandler CreateHandler() =>
        new(_projectRepository, _contractRepository, _milestoneRepository, _ticketRepository, _approvalRepository, _currentClientRoom);

    [Fact]
    public async Task Handle_ComputesTicketProgress_FromLiveTicketState()
    {
        // Arrange — project.Id (auto-generated by Create) is what every
        // other entity and repository stub must key off, not a separately
        // generated id.
        var project = Project.Create(Guid.NewGuid(), "Frontend redesign", "var(--tp-cat-1)", Guid.NewGuid());
        var contract = Contract.Create(project.TenantId, project.Id, "Meridian SOW", Guid.NewGuid());
        var milestone = Milestone.Create(project.TenantId, project.Id, contract.Id, "Milestone 2", Guid.NewGuid());
        var doneTicket = Ticket.Create(project.TenantId, project.Id, "Ship it", Guid.NewGuid());
        doneTicket.ChangeStatus(TicketStatus.Done, 0);
        var openTicket = Ticket.Create(project.TenantId, project.Id, "Polish it", Guid.NewGuid());

        _currentClientRoom.ProjectId.Returns(project.Id);
        _projectRepository.GetByIdAsync(project.Id, Arg.Any<CancellationToken>()).Returns(project);
        _contractRepository.GetByProjectIdAsync(project.Id, Arg.Any<CancellationToken>()).Returns(new List<Contract> { contract });
        _milestoneRepository.GetByContractIdAsync(contract.Id, Arg.Any<CancellationToken>()).Returns(new List<Milestone> { milestone });
        _ticketRepository.GetByMilestoneIdAsync(milestone.Id, Arg.Any<CancellationToken>()).Returns(new List<Ticket> { doneTicket, openTicket });
        _approvalRepository.GetByMilestoneIdAsync(milestone.Id, Arg.Any<CancellationToken>()).Returns((Approval?)null);
        var handler = CreateHandler();

        // Act
        var result = await handler.Handle(new GetClientRoomSummaryQuery(), CancellationToken.None);

        // Assert
        result.ProjectName.Should().Be("Frontend redesign");
        var milestoneDto = result.Contracts.Single().Milestones.Single();
        milestoneDto.TicketsTotal.Should().Be(2);
        milestoneDto.TicketsDone.Should().Be(1);
        milestoneDto.ProgressPercentage.Should().Be(50);
        milestoneDto.IsApproved.Should().BeFalse();
    }

    [Fact]
    public async Task Handle_WithNoTickets_ProgressIsZero_NotDivideByZeroError()
    {
        // Arrange
        var project = Project.Create(Guid.NewGuid(), "Frontend redesign", "var(--tp-cat-1)", Guid.NewGuid());
        var contract = Contract.Create(project.TenantId, project.Id, "Meridian SOW", Guid.NewGuid());
        var milestone = Milestone.Create(project.TenantId, project.Id, contract.Id, "Milestone 1", Guid.NewGuid());

        _currentClientRoom.ProjectId.Returns(project.Id);
        _projectRepository.GetByIdAsync(project.Id, Arg.Any<CancellationToken>()).Returns(project);
        _contractRepository.GetByProjectIdAsync(project.Id, Arg.Any<CancellationToken>()).Returns(new List<Contract> { contract });
        _milestoneRepository.GetByContractIdAsync(contract.Id, Arg.Any<CancellationToken>()).Returns(new List<Milestone> { milestone });
        _ticketRepository.GetByMilestoneIdAsync(milestone.Id, Arg.Any<CancellationToken>()).Returns(new List<Ticket>());
        _approvalRepository.GetByMilestoneIdAsync(milestone.Id, Arg.Any<CancellationToken>()).Returns((Approval?)null);
        var handler = CreateHandler();

        // Act
        var result = await handler.Handle(new GetClientRoomSummaryQuery(), CancellationToken.None);

        // Assert
        var milestoneDto = result.Contracts.Single().Milestones.Single();
        milestoneDto.TicketsTotal.Should().Be(0);
        milestoneDto.ProgressPercentage.Should().Be(0);
    }

    [Fact]
    public async Task Handle_ReflectsApprovalState()
    {
        // Arrange
        var project = Project.Create(Guid.NewGuid(), "Frontend redesign", "var(--tp-cat-1)", Guid.NewGuid());
        var contract = Contract.Create(project.TenantId, project.Id, "Meridian SOW", Guid.NewGuid());
        var milestone = Milestone.Create(project.TenantId, project.Id, contract.Id, "Milestone 1", Guid.NewGuid());
        var approval = Approval.Create(project.TenantId, project.Id, milestone.Id, Guid.NewGuid());

        _currentClientRoom.ProjectId.Returns(project.Id);
        _projectRepository.GetByIdAsync(project.Id, Arg.Any<CancellationToken>()).Returns(project);
        _contractRepository.GetByProjectIdAsync(project.Id, Arg.Any<CancellationToken>()).Returns(new List<Contract> { contract });
        _milestoneRepository.GetByContractIdAsync(contract.Id, Arg.Any<CancellationToken>()).Returns(new List<Milestone> { milestone });
        _ticketRepository.GetByMilestoneIdAsync(milestone.Id, Arg.Any<CancellationToken>()).Returns(new List<Ticket>());
        _approvalRepository.GetByMilestoneIdAsync(milestone.Id, Arg.Any<CancellationToken>()).Returns(approval);
        var handler = CreateHandler();

        // Act
        var result = await handler.Handle(new GetClientRoomSummaryQuery(), CancellationToken.None);

        // Assert
        var milestoneDto = result.Contracts.Single().Milestones.Single();
        milestoneDto.IsApproved.Should().BeTrue();
        milestoneDto.ApprovedAt.Should().Be(approval.ApprovedAt);
    }
}
